const siteRouter = require('./site')
const productRouter = require('./product')
const categoryRouter = require('./category')
const detailRouter = require('./detail')
const cartRouter = require('./cart')
const checkOutRouter = require('./checkOut')
const adminRouter = require('./admin')
const accountRouter = require('./account')
const checkLogin = require('../app/midddleware/checkLogin')
const checkAdmin = require('../app/midddleware/checkAdmin')
const getAccount = require('../app/midddleware/getAccount')
const getCategory = require('../app/midddleware/categoryLocals')
function route(app) {
    app.use('*', getCategory, getAccount)
    app.use('/', siteRouter)
    app.use('/product', productRouter)
    app.use('/detail-product', detailRouter)
    app.use('/category', categoryRouter)
    app.use('/cart', cartRouter)
    app.use('/check-out', checkOutRouter)
    app.use('/admin', checkLogin, checkAdmin, adminRouter)
    app.use('/', accountRouter)
}
module.exports = route