const siteRouter = require('./site')
const productRouter = require('./product')
const categoryRouter = require('./category')
const detailRouter = require('./detail')
const cartRouter = require('./cart')
const checkOutRouter = require('./checkOut')
const adminRouter = require('./admin')
const accountRouter = require('./account')
const checkLogin = require('../app/midddleware/checkLogin')
const checkAuthor = require('../app/midddleware/checkAuthor')
const getAccount = require('../app/midddleware/getAccount')
const getCategory = require('../app/midddleware/getCategory')
const infoPayment = require('./infoPayment')
const getTotalCart = require('../app/midddleware/getTotalCart')
function route(app) {
    app.use('*', getTotalCart, getAccount)
    app.use('/', siteRouter)
    app.use('/product', productRouter)
    app.use('/detail-product', detailRouter)
    app.use('/category', getCategory, categoryRouter)
    app.use('/cart', cartRouter)
    app.use('/check-out', checkLogin, checkOutRouter)
    app.use('/admin', checkLogin, checkAuthor, adminRouter)
    app.use('/', accountRouter)
    app.use('/info-payment', infoPayment)
}
module.exports = route